/** Seed tasks shipped with FlowDesk (same as original prototype). */
export const SEED_TASKS = [
  {
    id: "t1",
    title: "Design 10 Static Posts — Dinamoo May",
    brand: "Dinamoo",
    assignedTo: "poornima",
    assignedBy: "rushabh",
    priority: "High",
    due: "2026-05-20",
    status: "in_progress",
    desc: "Create 10 static posts for Dinamoo's May calendar. Use brand colors — gold & black.",
    createdAt: "2026-05-01",
    timeline: [
      { by: "rushabh", action: "Assigned task", at: "2026-05-01" },
      { by: "poornima", action: "Started work", at: "2026-05-02" },
    ],
  },
  {
    id: "t2",
    title: "Script 3 Reels — Dinamoo",
    brand: "Dinamoo",
    assignedTo: "aastha",
    assignedBy: "rushabh",
    priority: "High",
    due: "2026-05-15",
    status: "submitted",
    desc: "Write scripts for 3 product reels. Each reel 30-45 seconds. Tone: confident, modern.",
    createdAt: "2026-05-01",
    timeline: [
      { by: "rushabh", action: "Assigned task", at: "2026-05-01" },
      { by: "aastha", action: "Started work", at: "2026-05-02" },
      {
        by: "aastha",
        action: "Submitted for review",
        at: "2026-05-08",
        note: "Scripts ready, added hook variations too.",
      },
    ],
  },
  {
    id: "t3",
    title: "Edit 3 Reels — Quick Furnish",
    brand: "Quick Furnish",
    assignedTo: "anthony",
    assignedBy: "bhautik",
    priority: "Medium",
    due: "2026-05-18",
    status: "issue",
    desc: "Edit 3 shoot reels for Quick Furnish. Use upbeat BGM. Subtitles required.",
    createdAt: "2026-05-02",
    timeline: [
      { by: "bhautik", action: "Assigned task", at: "2026-05-02" },
      { by: "anthony", action: "Started work", at: "2026-05-03" },
      {
        by: "anthony",
        action: "Raised issue",
        at: "2026-05-06",
        note: "Raw footage not received from client yet. Waiting on Bhautik to follow up.",
      },
    ],
  },
  {
    id: "t4",
    title: "15 Stories — Minotti Ahmedabad",
    brand: "Minotti Ahmedabad",
    assignedTo: "poornima",
    assignedBy: "rushabh",
    priority: "Medium",
    due: "2026-05-22",
    status: "assigned",
    desc: "Design 15 Instagram stories. Luxury tone. Use Minotti brand palette.",
    createdAt: "2026-05-03",
    timeline: [{ by: "rushabh", action: "Assigned task", at: "2026-05-03" }],
  },
  {
    id: "t5",
    title: "Scrumfolks May Blogs (5)",
    brand: "Scrumfolks",
    assignedTo: "aastha",
    assignedBy: "vishven",
    priority: "Medium",
    due: "2026-05-25",
    status: "reviewed",
    desc: "Write 5 blogs for Scrumfolks. Topics: AI in marketing, Brand storytelling, Social trends.",
    createdAt: "2026-05-01",
    timeline: [
      { by: "vishven", action: "Assigned task", at: "2026-05-01" },
      { by: "aastha", action: "Started work", at: "2026-05-02" },
      {
        by: "aastha",
        action: "Submitted for review",
        at: "2026-05-07",
        note: "All 5 blogs done. SEO optimized.",
      },
      {
        by: "vishven",
        action: "Reviewed & approved",
        at: "2026-05-09",
        note: "Excellent work. Approved.",
      },
    ],
  },
  {
    id: "t6",
    title: "GCA Campaign — 3 Posts",
    brand: "GCA",
    assignedTo: "aarti",
    assignedBy: "rushabh",
    priority: "Urgent",
    due: "2026-05-10",
    status: "closed",
    desc: "3 campaign creatives for GCA. High impact visuals required.",
    createdAt: "2026-04-28",
    timeline: [
      { by: "rushabh", action: "Assigned task", at: "2026-04-28" },
      { by: "aarti", action: "Submitted for review", at: "2026-05-08" },
      { by: "rushabh", action: "Reviewed & approved", at: "2026-05-09" },
      {
        by: "rushabh",
        action: "Closed task",
        at: "2026-05-10",
        note: "Great work Aarti! Delivered on time.",
      },
    ],
  },
  {
    id: "t7",
    title: "SmartiQo May Social Calendar",
    brand: "SmartiQo",
    assignedTo: "kalgi",
    assignedBy: "anushka",
    priority: "High",
    due: "2026-05-19",
    status: "changes",
    desc: "Design full May calendar for SmartiQo — 9 statics + 2 reels cover.",
    createdAt: "2026-05-04",
    timeline: [
      { by: "anushka", action: "Assigned task", at: "2026-05-04" },
      { by: "kalgi", action: "Submitted for review", at: "2026-05-08" },
      {
        by: "anushka",
        action: "Requested changes",
        at: "2026-05-09",
        note: "Fonts need to match brand guidelines. Revise 3 posts.",
      },
    ],
  },
] as const;
